require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReportPeriodsController do

  # This should return the minimal set of attributes required to create a valid
  # ReportPeriod. As you add validations to ReportPeriod, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "week_ending" => "2013-02-08" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReportPeriodsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all report_periods as @report_periods" do
      report_period = ReportPeriod.create! valid_attributes
      get :index, {}, valid_session
      assigns(:report_periods).should eq([report_period])
    end
  end

  describe "GET show" do
    it "assigns the requested report_period as @report_period" do
      report_period = ReportPeriod.create! valid_attributes
      get :show, {:id => report_period.to_param}, valid_session
      assigns(:report_period).should eq(report_period)
    end
  end

  describe "GET new" do
    it "assigns a new report_period as @report_period" do
      get :new, {}, valid_session
      assigns(:report_period).should be_a_new(ReportPeriod)
    end
  end

  describe "GET edit" do
    it "assigns the requested report_period as @report_period" do
      report_period = ReportPeriod.create! valid_attributes
      get :edit, {:id => report_period.to_param}, valid_session
      assigns(:report_period).should eq(report_period)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReportPeriod" do
        expect {
          post :create, {:report_period => valid_attributes}, valid_session
        }.to change(ReportPeriod, :count).by(1)
      end

      it "assigns a newly created report_period as @report_period" do
        post :create, {:report_period => valid_attributes}, valid_session
        assigns(:report_period).should be_a(ReportPeriod)
        assigns(:report_period).should be_persisted
      end

      it "redirects to the created report_period" do
        post :create, {:report_period => valid_attributes}, valid_session
        response.should redirect_to(ReportPeriod.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved report_period as @report_period" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReportPeriod.any_instance.stub(:save).and_return(false)
        post :create, {:report_period => { "week_ending" => "invalid value" }}, valid_session
        assigns(:report_period).should be_a_new(ReportPeriod)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReportPeriod.any_instance.stub(:save).and_return(false)
        post :create, {:report_period => { "week_ending" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested report_period" do
        report_period = ReportPeriod.create! valid_attributes
        # Assuming there are no other report_periods in the database, this
        # specifies that the ReportPeriod created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ReportPeriod.any_instance.should_receive(:update_attributes).with({ "week_ending" => "2013-02-08" })
        put :update, {:id => report_period.to_param, :report_period => { "week_ending" => "2013-02-08" }}, valid_session
      end

      it "assigns the requested report_period as @report_period" do
        report_period = ReportPeriod.create! valid_attributes
        put :update, {:id => report_period.to_param, :report_period => valid_attributes}, valid_session
        assigns(:report_period).should eq(report_period)
      end

      it "redirects to the report_period" do
        report_period = ReportPeriod.create! valid_attributes
        put :update, {:id => report_period.to_param, :report_period => valid_attributes}, valid_session
        response.should redirect_to(report_period)
      end
    end

    describe "with invalid params" do
      it "assigns the report_period as @report_period" do
        report_period = ReportPeriod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReportPeriod.any_instance.stub(:save).and_return(false)
        put :update, {:id => report_period.to_param, :report_period => { "week_ending" => "invalid value" }}, valid_session
        assigns(:report_period).should eq(report_period)
      end

      it "re-renders the 'edit' template" do
        report_period = ReportPeriod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReportPeriod.any_instance.stub(:save).and_return(false)
        put :update, {:id => report_period.to_param, :report_period => { "week_ending" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested report_period" do
      report_period = ReportPeriod.create! valid_attributes
      expect {
        delete :destroy, {:id => report_period.to_param}, valid_session
      }.to change(ReportPeriod, :count).by(-1)
    end

    it "redirects to the report_periods list" do
      report_period = ReportPeriod.create! valid_attributes
      delete :destroy, {:id => report_period.to_param}, valid_session
      response.should redirect_to(report_periods_url)
    end
  end

end
