require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StatusReportsController do

  # This should return the minimal set of attributes required to create a valid
  # StatusReport. As you add validations to StatusReport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "project" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StatusReportsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all status_reports as @status_reports" do
      status_report = StatusReport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:status_reports).should eq([status_report])
    end
  end

  describe "GET show" do
    it "assigns the requested status_report as @status_report" do
      status_report = StatusReport.create! valid_attributes
      get :show, {:id => status_report.to_param}, valid_session
      assigns(:status_report).should eq(status_report)
    end
  end

  describe "GET new" do
    it "assigns a new status_report as @status_report" do
      get :new, {}, valid_session
      assigns(:status_report).should be_a_new(StatusReport)
    end
  end

  describe "GET edit" do
    it "assigns the requested status_report as @status_report" do
      status_report = StatusReport.create! valid_attributes
      get :edit, {:id => status_report.to_param}, valid_session
      assigns(:status_report).should eq(status_report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StatusReport" do
        expect {
          post :create, {:status_report => valid_attributes}, valid_session
        }.to change(StatusReport, :count).by(1)
      end

      it "assigns a newly created status_report as @status_report" do
        post :create, {:status_report => valid_attributes}, valid_session
        assigns(:status_report).should be_a(StatusReport)
        assigns(:status_report).should be_persisted
      end

      it "redirects to the created status_report" do
        post :create, {:status_report => valid_attributes}, valid_session
        response.should redirect_to(StatusReport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved status_report as @status_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatusReport.any_instance.stub(:save).and_return(false)
        post :create, {:status_report => { "project" => "invalid value" }}, valid_session
        assigns(:status_report).should be_a_new(StatusReport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatusReport.any_instance.stub(:save).and_return(false)
        post :create, {:status_report => { "project" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested status_report" do
        status_report = StatusReport.create! valid_attributes
        # Assuming there are no other status_reports in the database, this
        # specifies that the StatusReport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StatusReport.any_instance.should_receive(:update_attributes).with({ "project" => "" })
        put :update, {:id => status_report.to_param, :status_report => { "project" => "" }}, valid_session
      end

      it "assigns the requested status_report as @status_report" do
        status_report = StatusReport.create! valid_attributes
        put :update, {:id => status_report.to_param, :status_report => valid_attributes}, valid_session
        assigns(:status_report).should eq(status_report)
      end

      it "redirects to the status_report" do
        status_report = StatusReport.create! valid_attributes
        put :update, {:id => status_report.to_param, :status_report => valid_attributes}, valid_session
        response.should redirect_to(status_report)
      end
    end

    describe "with invalid params" do
      it "assigns the status_report as @status_report" do
        status_report = StatusReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatusReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => status_report.to_param, :status_report => { "project" => "invalid value" }}, valid_session
        assigns(:status_report).should eq(status_report)
      end

      it "re-renders the 'edit' template" do
        status_report = StatusReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatusReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => status_report.to_param, :status_report => { "project" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested status_report" do
      status_report = StatusReport.create! valid_attributes
      expect {
        delete :destroy, {:id => status_report.to_param}, valid_session
      }.to change(StatusReport, :count).by(-1)
    end

    it "redirects to the status_reports list" do
      status_report = StatusReport.create! valid_attributes
      delete :destroy, {:id => status_report.to_param}, valid_session
      response.should redirect_to(status_reports_url)
    end
  end

end
